# Versão da sintaxe do Docker Compose. A versão '3.8' é uma boa escolha, moderna e com muitos recursos.
version: '3.8'

# Seção que define os serviços (containers) que compõem sua aplicação.
# Cada chave sob 'services' é o nome de um serviço, que também pode ser usado
# como hostname para comunicação entre os containers dentro da rede do Compose.
services:
  # 1. Serviço do Banco de Dados MySQL
  db:
    image: mysql:8.0 # Define a imagem Docker a ser usada. Usamos a versão 8.0 do MySQL.
    container_name: fonar_db_container # Nome explícito para o container (facilita a identificação no Docker Desktop)

    # Variáveis de ambiente que serão passadas para o container MySQL.
    # ESSAS SÃO AS VARIÁVEIS DO BANCO DE DADOS MYSQL!
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Senha do usuário 'root' do MySQL. Mude para uma senha forte em produção!
      MYSQL_DATABASE: fonar_db # Nome do banco de dados que será criado automaticamente ao iniciar o container.
      MYSQL_USER: devance # <--- ALTERADO: Usuário para sua aplicação
      MYSQL_PASSWORD: dev123 # <--- ALTERADO: Senha para o usuário da aplicação

    # Mapeamento de portas: "HOST_PORT:CONTAINER_PORT".
    # Isso expõe a porta 3306 do container MySQL para a porta 3306 da sua máquina host.
    ports:
      - "3306:3306"

    # Volumes: Usado para persistir dados. Se o container for removido, os dados não serão perdidos.
    volumes:
      - db_data:/var/lib/mysql

    # Healthcheck: (Recomendado) Define um comando para verificar a saúde do serviço.
    # Adaptação do usuário no healthcheck:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "devance", "-pdev123"] # <--- ALTERADO
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # 2. Serviço da Aplicação Spring Boot (devance-backend)
  app:
    build:
      context: .
      dockerfile: Dockerfile

    image: devance-backend-app-fonar
    container_name: fonar_app_container

    ports:
      - "8080:8080"

    depends_on:
      db:
        condition: service_healthy

    # Variáveis de ambiente para a aplicação Spring Boot.
    # ESTAS SÃO AS VARIÁVEIS DA SUA APLICAÇÃO SPRING BOOT!
    environment:
      # URL de conexão corrigida, incluindo 'allowPublicKeyRetrieval=True'
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fonar_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=True
      SPRING_DATASOURCE_USERNAME: devance # <--- ALTERADO: Deve corresponder a MYSQL_USER em 'db'
      SPRING_DATASOURCE_PASSWORD: dev123 # <--- ALTERADO: Deve corresponder a MYSQL_PASSWORD em 'db'
      # spring.devtools.restart.enabled: false
      # logging.level.org.springframework: DEBUG
      # logging.level.org.hibernate: DEBUG

    # volumes:
    #   - ./target/classes:/app/classes
    #   - ~/.m2:/root/.m2

# Seção que define os volumes nomeados.
volumes:
  db_data: